apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mzv599rzl-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mzv599rzl-java-springboot-gitops